[package]
name = "oxidized_armoury"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "reflective_loader"
path = "src/ReflectiveLoader/main.rs"

[dependencies]
